<x-backend.layouts.master>
    <h1>Wlcome to dashboard</h1>
    <table class="w-100 table table-dark table-hover">
                <thead>
                    <tr>
                        <th>sl.</th>
                        <th>sl.</th>
                        <th>sl.</th>
                        <th>sl.</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>01</td>
                        <td>01</td>
                        <td>01</td>
                        <td>01</td>
                    </tr>
                    <tr>
                        <td>01</td>
                        <td>01</td>
                        <td>01</td>
                        <td>01</td>
                    </tr>
                    <tr>
                        <td>01</td>
                        <td>01</td>
                        <td>01</td>
                        <td>01</td>
                    </tr>
                    <tr>
                        <td>01</td>
                        <td>01</td>
                        <td>01</td>
                        <td>01</td>
                    </tr>
                </tbody>
               </table>
</x-backend.layouts.master>